// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.

package jaeger

import (
	"bytes"
	"context"
	"fmt"
	"github.com/fuyibing/log/v5/tracers/tracer_jaeger/thrift"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

func init() {
}
