#
# log client based on yaml configuration
#
adapter: "file"
level: "debug"
time-format: "15:04:05.999999"

# Batch mode
batch-concurrency: 3
batch-limit: 150

# Open tracing.

# usage: adapter=file
#        use default if fields not configured
file:

# usage: adapter=kafka
#        use default if fields not configured
kafka:
  topic-name: "topic"

# usage: adapter=term
term:
  color: true
